#serviceAccount: SOME_SERVICE_ACCOUNT
#tensorboard: SOME_TENSORBOARD
baseOutputDirectory:
  outputUriPrefix: gs://bucket_olg_01/training-output/
workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-2
  replicaCount: 1
  pythonPackageSpec:
    executorImageUri: europe-docker.pkg.dev/vertex-ai/training/tf-cpu.2-7:latest
    packageUris: gs://SOMEWHERE
    pythonModule: trainer.task
    args:
      - --data-location=gs://bucket_olg_01/output/
      - --tft-location=gs://bucket_olg_01/output/transform_fn/
      - --batch-size=4096
      - --epochs=30